images:
  airflow:
    repository: my-dags
    tag: ~
    # Specifying digest takes precedence over tag.
    digest: ~
    pullPolicy: IfNotPresent

postgresql:
  image:
    repository: bitnamilegacy/postgresql
    tag: 16.1.0-debian-11-r15
